### ISSUE TITLE
[BUG] Groups 3.0.56 - Adding a group event to multiple groups creates a "loop"

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1058]
After creating an event, and selecting another group to add it to, I get taken to the other group and then when trying to back out using the arrow in the upper left corner, I get prompted to "save changes", which duplicates the event in the same group.  Sorry this isn't very clear, I'll try to add better documentation if needed.

**Comment by dobromirdobrev** [comment]
Fixed in version 3.0.60. Please verify and let us know if you face any issues.

P.S. I reopen the issue because github closed it automatically.

**Comment by kpecknold** [comment]
@dobromirdobrev 
This is still a problem in 3.0.60
To reproduce, make sure you are admin of more than 1 group
Go into 1 group, create a new event, adding all required fields, then "Create Event". When prompted to add to other groups, do  that. Then note you are returned to the event screen, still in edit/create mode. Even though you are finished editing, you have already created the event. It is natural at this point to back out using top left < rather than "Create Event" again. When you do this, you get prompted to save changes, and if you say yes, you get looped through the save to other groups a second time.

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,

I'm unable to reproduce the behaviour that you explain in 3.0.60.
This is the scenario that I do:

0. Prerequisites - I'm an admin of two groups "DD New group" and "DD second group"
1. Go to Groups and select "DD second group"
2. Tap on the "plus" sign to add a group event and select "Create new event"
3. Populate the required fields - "Category", "Event title", "Start Date", "Start Time", "End date" and "End Time"
4. Tap "Create Event"
5. When prompted, select the other group "DD New group"
6. When finished, the app redirects to the Event detail panel in "preview" mode
7. Tap back arrow at top left - the app shows correctly the Group Detail panel

In this scenario, I was neither prompted to "Save changes", nor looped through the save to other groups.

Here is a video of the above scenario. https://drive.google.com/file/d/1uEQFEwwzc_GjiIkX68DGk605865WIgUj/view?usp=sharing

If this is not the scenario that you follow or if you still observe any issues, please let us know the exact steps.

cc @pmarkhennessy
