### ISSUE TITLE
[BUG] Broken External Link Fields for Events: 2FA loop Issue

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3430]
When creating an event via the Event Feed or Groups > Create Event, the below three fields still open up WITHIN the app, not allowing for links that require 2FA. 
1) "Add External Link for Registration" under Event Registration  
2) "Add Event Website Link" 
3) "Online URL" under “Event Type and Location” 

Please have these fields open outside of the app to avoid this issue.  

To reproduce, enter this test link to any of the above fields when creating an event in the app: https://forms.illinois.edu/sec/886800590 

**Expected behavior**
I expect event creators to be able to share links that require someone to login with their netid to access registration, online events, and/or event details.

Android 13, Pixel 6
Illinois app 5.0.33

![Screenshot_20230724-120708](https://github.com/rokwire/illinois-app/assets/1044905/b664e0ae-3492-4773-8437-cc527f53312b)

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.47

**Comment by vburgett** [comment]
In 5.0.52, I can add "http://" and "confirm the url" for the "Add Event Website Link." However after tapping "Update Event," the "website" button on the event details panel still does not work. When going back into the event admin settings, I see that the edit did not stick and once again there is no "http://" in the "Add Event Website Link" field. 

I am testing the event "World Photo Day" tomorrow 12am-12pm.

**Comment by vburgett** [comment]
Confirmed as working in 5.0.52. Thank you!
