### ISSUE TITLE
[BUG] Unpublishing an event should result in that event NOT displaying for Group members 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3907]
**Needs fixing**
Unpublishing an event in a Group continues to display that event for Group members when:
- An event is created via the admin website
- That event is added to a Group via the app
- That event is set to unpublish via the admin website

Unpublishing an event following the above steps should _not_ result in that event displaying for Group members. 

**Below is what _is_ working, as expected:**
Unpublishing an event in a Group does NOT display that event for Group members when:
- An event is created via the admin website
- The event is published to a Group via the admin website
- That event is set to unpublish via the admin website

This issue is also in the [admin website repo ticket 521](https://github.com/rokwire/illinois_admin/issues/521).

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, I believe the issue is in api/group/{group-id}/v3/load API in Group BB.

**Comment by dobromirdobrev** [comment]
@vburgett ,

This is fixed on the backend. Please verify it with the latest app version. Thanks.

**Comment by vburgett** [comment]
Thank you, @dobromirdobrev. This worked in the app 5.1.22. There is still an issue on the admin website side that I will post here https://github.com/rokwire/illinois_admin/issues/521
