### ISSUE TITLE
[BUG] Replies to Group messages do not work

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4844]
1. Send a message to one member in a group that you administer (group should have more than one member)
2. Confirm that group member never gets notified about the message
3. Try to reply to your own message.
4. Get the attached error.
5. Have the group member reply to your message
6. The group member can see their reply but there is not any indication of a reply under Messages
7. Group member sees their reply but the admin never sees the reply even after waiting and then quitting and restarting the app

An admin _can_ reply to a message that involves all group members. 
The group does have "send replies" toggled on under advanced group settings.
This issue was tested in the private group "SHCI Design + Research"

![Image](https://github.com/user-attachments/assets/1a1c614c-fbfb-40d7-8282-2f5238f16982)
 
![Image](https://github.com/user-attachments/assets/edab3f7e-21fb-42ae-90d4-d1b6dc20f484)

![Image](https://github.com/user-attachments/assets/fd0a1018-3a1e-42fd-9bfb-6b81a996c504)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
This is fixed in version 6.1.66 of the Illinois app. Please note that it is fixed for newly created group posts/messages.

**Comment by vburgett** [comment]
@dobromirdobrev In 6.1.66, I can reply to my own message now without an error, and a group member can reply to my message. 

The specific members/admins in the message still do not get notified about replies, but I am hoping that gets fixed with #2938 Is that true or should I open a separate ticket?

There is still no indication of replies on the message card under the Messages tab in the Group details panel. In the below example of a message card, I expect to see "2 Replies" like I would on a Post card.

![Image](https://github.com/user-attachments/assets/b29ae21c-1670-4da6-bc90-94206424e2ce)
![Image](https://github.com/user-attachments/assets/32f23519-4f20-4cfb-aae4-0541e1dd1675)
![Image](https://github.com/user-attachments/assets/eaddbad6-5e15-49c5-92a4-b22e28c47a6a)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

> The specific members/admins in the message still do not get notified about replies, but I am hoping that gets fixed with #2938 Is that true or should I open a separate ticket?

Yes, this is true and you don't need to open a separate ticket. Currently the backend team is working on that task in https://github.com/rokwire/social-building-block/issues/143


> There is still no indication of replies on the message card under the Messages tab in the Group details panel. In the below example of a message card, I expect to see "2 Replies" like I would on a Post card.

This is fixed in version 6.1.69 and/or 6.2.1.

**Comment by vburgett** [comment]
I'll close this ticket and keep an eye on https://github.com/rokwire/social-building-block/issues/143 Thank you!
