### ISSUE TITLE
[BUG] Recurring Monthly Events Display Incorrect Recurrence Dates

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4992]
1. In the group "Enneagram Enthusiasts," I created a recurring monthly event on the third Wednesday. The first event of the recurrence was set to Wednesday, April 16. See screenshot.

2. The recurrences for the following two months were calculated as Tuesday, May 20 and Tuesday, June 17.

I expect an event set to recur monthly on Wednesdays to only show events on Wednesdays.   

Dev 7.0.10 website

![Image](https://github.com/user-attachments/assets/5603c5aa-66b5-4945-921a-0b1d72a38de9)

![Image](https://github.com/user-attachments/assets/6ad4d207-a9d2-4e96-a60b-876e2ea5232d)

**Comment by dobromirdobrev** [comment]
@vburgett ,

I'm not able to re-create the problem. I double-checked the source code, created quite a few recurring events and all seems to be correct. 

I see that this is an old issue. There have been some fixed with recurring events since then. So, could you please check once again if this is reproducible to you with the latest version that you have (or the web app) on dev? 
If "yes" then please give us details - time zone, week days, time etc

Thanks!

**Comment by vburgett** [comment]
Unfortunately the issue still exists in 7.1.7 via the web. I followed the same steps as outlined above. You can see all my event settings in this screen recording. @dobromirdobrev 

https://github.com/user-attachments/assets/e5db42b8-112c-4a5d-8a39-f0efa171140e

:

**Comment by dobromirdobrev** [comment]
@vburgett ,

Thank you for the video! It helped us to identify the problem. It should be fixed in version 7.1.9. Please verify when you have a chance.

**Comment by vburgett** [comment]
Confirming that this is now fixed. Thank you!
