### ISSUE TITLE
[BUG] Report to group administrator notification bugs

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#5555]
On dev 7.3.28, a group member reported my direct message to me as a group admin from the ! icon in the upper right hand corner of our message panel.

As the group admin, I received the below notification. Once I tapped on the notification, I received an error message.

I expect to receive a notification that I can tap thru to the message without any html in the notification text. 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/c5da73dc-6231-4bae-a216-f2d60366f038" />

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/c574a056-f049-47c8-accb-0babbfe2889e" />

**Comment by mihail-varbanov** [comment]
@vburgett, it is said that https://github.com/rokwire/social-building-block/issues/244 has been fixed and deployed, so the problem must be resolved now. It does not involve any updates in the client app.

**Comment by vburgett** [comment]
@mihail-varbanov I am still receiving a notification with a "failed" tap thru and html in the notification text using 7.3.33 (prod, iPhone)

https://github.com/user-attachments/assets/90c56bc7-c22a-4434-b3db-9282cc50f93f

**Comment by mihail-varbanov** [comment]
@vburgett, this truncation was explicitly requested [here](https://github.com/rokwire/illinois-app/issues/4050#issuecomment-2192286724).

**Comment by vburgett** [comment]
@mihail-varbanov yes, we want to maintain notifications for posts and messages being truncated. 

Can the notifications for reporting a code of conduct issue be an exception? Otherwise these cases do not tap through to the results of what was reported but only the post in question.
