### ISSUE TITLE
[BUG] Event relative time error

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#626]
**Describe the bug**
An event might show "Tomorrow at [TIME]" as it's start time when the start time is actually the day after tomorrow.

**To Reproduce**
(Assuming this is being done today, Tuesday, July 27 at 5PM Central time)
1. Create an event in Events Manager with a Start Time of Thursday, July 29 at 6PM.
2. Open Illinois app and find that event, it will correctly shows "Jul 29 6PM"
![Screenshot (Jul 27, 2021 5_02_13 PM)](https://user-images.githubusercontent.com/11352701/127233593-6f7c9fb1-3330-4144-99ca-ab73f1ed0c86.png)
3. Change the start time to July 29 at 5PM in Events Manager. The date is left the same, only the time changes.
4. Open the Illinois app and find the event, it will incorrectly show "Tomorrow at 5PM"
![Screenshot (Jul 27, 2021 5_06_06 PM)](https://user-images.githubusercontent.com/11352701/127233821-de2faef7-721c-4414-929b-794ab190d5cd.png)

**Expected behavior**
The app should show "Jul 29 5PM" start time. July 29 is not tomorrow.

This also happens when an event is scheduled to start the next day during the current hour. In the app, for an event that starts tomorrow at 5pm, right now it will say "Today at 5pm" instead of "Tomorrow at 5pm"

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.6.10

**Comment by dobromirdobrev** [comment]
Hi @isaac-galvan ,
Thank you for your detailed description! It helped us to find the problem. It should be fixed now. Please verify it with version 2.6.12 and let us now if you face any other issues.

Reopening this issue so that the fix could be verified. Github closed it automatically.

**Comment by isaac-galvan** [comment]
Hey @dobromirdobrev thanks for working on this. I'm still seeing an incorrect label in 2.6.13-dev.

Right now, it's July 30 at 245pm. 
I have an event with a start time of July 31, 2 pm, then the app says "Tomorrow at 2pm", which is correct.
If I change the event start to August 1 at 2pm, then the app still says "Tomorrow at 2pm", which is incorrect.
I can change the date to August 2, and it says "Aug 2 at 2PM", which is correct.

I have an event with a start date of August  at 2pm.
In the events list, it shows as "Tomorrow at 2pm", which is not correct.

**Comment by isaac-galvan** [comment]
I tried in 2.6.14 in dev environment and still seeing the same issue.

**Comment by knguyenjahiel** [comment]
Closed: issue submitted 7/27/2021 and is not relevant to the present functionality and design. Submitter is no longer working with the Ill App
