### ISSUE TITLE
[BUG] MTD Bus Pass Not Showing to Illinois Residents

### ISSUE THREAD

**Issue by npvance2Illinois** [rokwire/illinois-app#936]
**Describe the bug**
When the role "illinois Resident" is selected in "Who Are You". The MTD Bus Pass is hidden from the wallet. Those people should still see the MTD Pass.

**To Reproduce**
1. Go to Settings - Personal Information - Who Are You
2. Select "Illinois Resident"
3. Go to the Wallet.
4. The MTD Pass will disappear

**Expected behavior**
The person should still be able to access the MTD bus pass as long as they are signed in.

**Screenshots**

**Comment by mihail-varbanov** [comment]
Fixed in 2.8.0

**Comment by Priyaravi8** [comment]
@pmarkhennessy I still reproduce this error with Role "Illinois Resident" in version 2.8.1

**Comment by Priyaravi8** [comment]
Install the Illinois app 2.8.1
Select the role "Resident" in the Who are you screen 
complete the onboarding steps
Verify your phone number and confirm it with the code
Tap on the Wallet menu at the bottom of the screen

IOS and Android - Actual Result - Wallet screen is Empty 

Screen shot 
![MTD](https://user-images.githubusercontent.com/26231179/141855589-a7dd4ec7-5e9b-47cd-86ce-b51e93690f75.png)
-

**Comment by mihail-varbanov** [comment]
@Priyaravi8, the talent chooser service for version 2.8 was not properly configured on production. This should be resolved now. CC @pmarkhennessy.

**Comment by vburgett** [comment]
We no longer have Illinois Resident as an option so I am closing this ticket.
